# See: https://docs.readthedocs.io/en/latest/config-file/v2.html
version: 2

build:
  image: latest

python:
  version: '3.10'
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
